
pool:
  name: Azure Pipelines

variables:
  AzureSubscription: 'Service-Principal_AZ4DB_pipeline-AU'
  WebAppName: 'shem-nodeapi-ue2546imlz23k'
  WebAppRG: 'az4db-wissenstransfer'

stages:
- stage: Build
  displayName: "Build"
  jobs:
  - job: Build
    displayName: "Build"
    steps:
    - task: Npm@1
      displayName: Restore
      inputs:
        command: ci
        workingDir: './workshop-node-api'
    - task: Npm@1
      displayName: Build
      inputs:
        command: custom
        customCommand: run build
        workingDir: './workshop-node-api'
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/workshop-node-api'
        Contents: |
          package.json
          package-lock.json
        TargetFolder: '$(System.DefaultWorkingDirectory)/workshop-node-api/dist'
    - task: Npm@1
      displayName: Restore
      inputs:
        command: custom
        customCommand: ci --production --prefix ./dist
        workingDir: './workshop-node-api'
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Artifact'
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/workshop-node-api/dist'
        artifactName: 'api'
        publishLocation: 'pipeline'
      condition: succeededOrFailed()
- stage: Release
  displayName: "Release"
  jobs:
  - job: Release
    displayName: "Release"
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: api
        targetPath: '$(Pipeline.Workspace)/api'
    - task: AzureWebApp@1
      inputs:
        azureSubscription: '$(AzureSubscription)'
        appType: 'webApp'
        appName: '$(WebAppName)'
        deployToSlotOrASE: true
        resourceGroupName: '$(WebAppRG)'
        slotName: 'swap'
        package: '$(Pipeline.Workspace)/api'
        # package: '$(System.DefaultWorkingDirectory)/**/*.zip'
        deploymentMethod: 'auto' # runFromPackage, auto
    - task: AzureAppServiceManage@0
      displayName: 'Start Swap Slot'
      inputs:
        azureSubscription: '$(AzureSubscription)'
        Action: 'Start Azure App Service'
        WebAppName: '$(WebAppName)'
        SpecifySlotOrASE: true
        ResourceGroupName: '$(WebAppRG)'
        Slot: swap
    - task: AzureAppServiceManage@0
      displayName: 'Swap Slots'
      inputs:
        azureSubscription: '$(AzureSubscription)'
        WebAppName: '$(WebAppName)'
        ResourceGroupName: '$(WebAppRG)'
        SourceSlot: swap
    - task: AzureAppServiceManage@0
      displayName: 'Stop Swap Slot'
      inputs:
        azureSubscription: '$(AzureSubscription)'
        Action: 'Stop Azure App Service'
        WebAppName: '$(WebAppName)'
        SpecifySlotOrASE: true
        ResourceGroupName: '$(WebAppRG)'
        Slot: swap
    # - task: AzureRmWebAppDeployment@4
    #   displayName: 'Deploy Azure App Service'
    #   inputs:
    #     azureSubscription: '$(AzureSubscription)'
    #     appType: '$(webApp)'
    #     WebAppName: '$(WebAppName)'
    #     deployToSlotOrASE: true
    #     ResourceGroupName: '$(WebAppRG)'
    #     SlotName: swap
    #     packageForLinux: '$(System.DefaultWorkingDirectory)/asa/drop/SpatialAnchorInformationServer.zip'
    #     enableCustomDeployment: true
    #     TakeAppOfflineFlag: false
    #     RemoveAdditionalFilesFlag: true
    #     ExcludeFilesFromAppDataFlag: false
