name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main
    paths:
      - "docs/**.md"
      - "mkdocs.yml"

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      # - name: Deploy docs
      #   uses: mhausenblas/mkdocs-deploy-gh-pages@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     CONFIG_FILE: mkdocs.yml
      #     EXTRA_PACKAGES: build-base
      #     REQUIREMENTS: requirements.txt

      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./site

      - name: Deploy documentation
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          mkdocs gh-deploy -b site -m 'Deployed {sha}' --force
          mkdocs --version
